from datetime import datetime
from fractions import Fraction
from math import isfinite
from typing import Any, List, Tuple


class EquityStitcher:
    """
    Builds a continuous stitched OOS equity curve
    from walk-forward window results.
    """

    @staticmethod
    def stitch(
        windows: List[Any],
    ) -> List[Tuple[datetime, float]]:
        """
        Return the canonical public float equity curve.
        """

        stitched_curve, _ = (
            EquityStitcher.stitch_with_exact(windows)
        )

        return stitched_curve

    @staticmethod
    def stitch_with_exact(
        windows: List[Any],
    ):
        """
        Return the public float curve plus an exact rational
        companion generated by the same stitching operation.

        The exact companion prevents float reconstruction noise
        from changing strict zero-boundary verdicts.
        """

        if not windows:
            return [], []

        stitched_curve: List[Tuple[datetime, float]] = []
        exact_curve = []

        capital_base = None
        exact_capital_base = None
        last_timestamp = None

        for window in windows:
            equity_curve = window.backtest_result.equity_curve
            window_index = getattr(
                window,
                "window_index",
                "unknown",
            )

            if not equity_curve:
                raise ValueError(
                    f"WFA window {window_index} requires "
                    f"OOS equity records"
                )

            try:
                window_start_equity = float(
                    equity_curve[0][1]
                )
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"WFA window {window_index} starting "
                    f"equity must be finite"
                ) from exc

            if not isfinite(window_start_equity):
                raise ValueError(
                    f"WFA window {window_index} starting "
                    f"equity must be finite"
                )

            if window_start_equity <= 0:
                raise ValueError(
                    f"WFA window {window_index} starting "
                    f"equity must be strictly positive"
                )

            if capital_base is not None and capital_base <= 0:
                raise ValueError(
                    "WFA stitching cannot continue after "
                    "non-positive equity"
                )

            window_start_exact = Fraction.from_float(
                window_start_equity
            )

            window_capital_base = (
                window_start_equity
                if capital_base is None
                else capital_base
            )
            window_exact_capital_base = (
                window_start_exact
                if exact_capital_base is None
                else exact_capital_base
            )

            # Preserve the existing finite/positive scaling
            # validity contract at the public-float boundary.
            scale = (
                1.0
                if window_capital_base == window_start_equity
                else window_capital_base / window_start_equity
            )

            if not isfinite(scale) or scale <= 0:
                raise ValueError(
                    "WFA stitching scale must be finite "
                    "and strictly positive"
                )

            last_exact_equity = None

            for point_index, (timestamp, raw_equity) in enumerate(
                equity_curve
            ):
                if not isinstance(timestamp, datetime):
                    raise TypeError(
                        "WFA equity timestamps must be datetime values"
                    )

                try:
                    equity = float(raw_equity)
                except (TypeError, ValueError) as exc:
                    raise ValueError(
                        f"WFA window {window_index} equity at "
                        f"index {point_index} must be finite"
                    ) from exc

                if not isfinite(equity):
                    raise ValueError(
                        f"WFA window {window_index} equity at "
                        f"index {point_index} must be finite"
                    )

                if last_timestamp is not None:
                    try:
                        non_increasing = timestamp <= last_timestamp
                    except TypeError as exc:
                        raise ValueError(
                            "WFA OOS equity timestamps must "
                            "be comparable"
                        ) from exc

                    if non_increasing:
                        raise ValueError(
                            "WFA OOS equity timestamps must be "
                            "strictly increasing and non-overlapping"
                        )

                equity_exact = Fraction.from_float(equity)

                if point_index == 0:
                    stitched_equity_exact = (
                        window_exact_capital_base
                    )
                else:
                    stitched_equity_exact = (
                        window_exact_capital_base
                        * equity_exact
                        / window_start_exact
                    )

                try:
                    stitched_equity = float(
                        stitched_equity_exact
                    )
                except OverflowError as exc:
                    raise ValueError(
                        "stitched WFA equity must be finite"
                    ) from exc

                if not isfinite(stitched_equity):
                    raise ValueError(
                        "stitched WFA equity must be finite"
                    )

                stitched_curve.append(
                    (timestamp, stitched_equity)
                )
                exact_curve.append(
                    (timestamp, stitched_equity_exact)
                )

                last_timestamp = timestamp
                last_exact_equity = stitched_equity_exact

            capital_base = stitched_curve[-1][1]
            exact_capital_base = last_exact_equity

        return stitched_curve, exact_curve
